### ISSUE TITLE
Playing age restricted videos doesnt work

### ISSUE THREAD

**Issue by savaonepunch** [Luuk-Dev/DiscordAudio#3]
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Error while getting video url
Sign in to confirm your age".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

**Comment by Luuk-Dev** [comment]
Hi,
I think I've already helped you on Discord as I got the same question in my DM. Anyways what you can do is install [the YT-Stream package](https://npmjs.com/package/yt-stream) which is being used to play YouTube songs. You can here set a custom cookie which should be a cookie from an account that has verified it's age. Once you've done this, you can use the `stream` function to get a `Readable` stream. You should play this `Readable` stream (which you can reach with the `stream` parameter in the object which gets returned in the `stream` function) instead of the YouTube url.

If you have any more questions, feel free to re-open this issue.

Kind regards,

Luuk
