### ISSUE TITLE
Everything is broken

### ISSUE THREAD

**Issue by imaperson1060** [Luuk-Dev/DiscordAudio#4]
Recently DiscordJS updated and changed a ton of stuff that was completely unnecessary, and now the library just throws
```
client.ws.on(discord_js_1.Constants.WSEvents.VOICE_SERVER_UPDATE, (payload) => {
                                                 ^

TypeError: Cannot read properties of undefined (reading 'VOICE_SERVER_UPDATE')
```
Fun.

**Comment by Luuk-Dev** [comment]
Hi @imaperson1060 ,

First of all thank you for reporting the issue.

Because of the new version this bug pops up. I am currently unable to update the DiscordAudio package, but here is a solution:
* Install the latest version of `@discordjs/voice` and `@discordjs/opus` (`npm i @discordjs/voice@0.11.0 @discordjs/opus@0.8.0`)
* Go to the file `/node_modules/discordaudio/package.json` and set the versions of `@discordjs/voice` to `^0.11.0` and `@discordjs/opus` to `^0.8.0`
* Go to the file `/node_modules/discordaudio/src/classes/player.js` and change line `156` to `adapterCreator: this.channel.guild.voiceAdapterCreator,`

Sorry for the inconvenience.

Kind regards,

Luuk

**Comment by Luuk-Dev** [comment]
A new version has been released which solves this issue.
